/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ChecklistSimplesRouteImport } from './routes/checklist-simples'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as IndexRouteImport } from './routes/index'

const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistSimplesRoute = ChecklistSimplesRouteImport.update({
  id: '/checklist-simples',
  path: '/checklist-simples',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/checklist-simples': typeof ChecklistSimplesRoute
  '/menu': typeof MenuRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/checklist-simples': typeof ChecklistSimplesRoute
  '/menu': typeof MenuRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/checklist-simples': typeof ChecklistSimplesRoute
  '/menu': typeof MenuRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checklist'
    | '/checklist-simples'
    | '/menu'
    | '/redefinir-senha'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checklist' | '/checklist-simples' | '/menu' | '/redefinir-senha'
  id:
    | '__root__'
    | '/'
    | '/checklist'
    | '/checklist-simples'
    | '/menu'
    | '/redefinir-senha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChecklistRoute: typeof ChecklistRoute
  ChecklistSimplesRoute: typeof ChecklistSimplesRoute
  MenuRoute: typeof MenuRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist-simples': {
      id: '/checklist-simples'
      path: '/checklist-simples'
      fullPath: '/checklist-simples'
      preLoaderRoute: typeof ChecklistSimplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChecklistRoute: ChecklistRoute,
  ChecklistSimplesRoute: ChecklistSimplesRoute,
  MenuRoute: MenuRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
